apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
     - image: nginx
       name: nginx
       ports:
       - containerPort: 80
       resources:
          requests:
             memory: "128Mi"
             cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
            

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
 # annotations: 
 #  external-dns.alpha.kubernetes.io/hostname: ekslab.abdelalitraining.com
spec:
  type: NodePort

 # type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

